# Generated by Django 4.0.6 on 2022-07-12 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('accountTypeLabel', models.CharField(max_length=255)),
                ('accountNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='credfica.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment', models.IntegerField()),
                ('installmentInterest', models.FloatField()),
                ('installmentValue', models.FloatField()),
                ('fullValue', models.FloatField()),
                ('comission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('clientId', models.UUIDField()),
                ('installmentId', models.IntegerField()),
                ('rateTableId', models.UUIDField()),
                ('installmentInterest', models.FloatField()),
                ('installmentInterestValue', models.FloatField()),
                ('cardName', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=255)),
                ('expirationDate', models.CharField(max_length=10)),
                ('cvc', models.CharField(max_length=4)),
                ('desiredValue', models.IntegerField()),
                ('totalLoan', models.FloatField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='credfica.customer')),
                ('installments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='credfica.installments')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='credfica.ratetable')),
            ],
        ),
        migrations.AddField(
            model_name='installments',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='credfica.ratetable'),
        ),
    ]
