# Generated by Django 4.0.6 on 2022-07-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credfica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bank',
        ),
        migrations.AddField(
            model_name='bank',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='credfica.customer'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='rateTableId',
            field=models.UUIDField(),
        ),
    ]
