# Generated by Django 4.0.6 on 2022-07-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credfica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='expirationDate',
            field=models.CharField(max_length=10),
        ),
    ]
