# Generated by Django 4.0.6 on 2022-07-11 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credfica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.IntegerField()),
                ('installmentInterest', models.FloatField()),
                ('installmentValue', models.FloatField()),
                ('fullValue', models.FloatField()),
                ('comission', models.FloatField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credfica.ratetable')),
            ],
        ),
    ]
