# Generated by Django 4.0.6 on 2022-07-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credfica', '0002_remove_customer_bank_bank_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='credfica.bank'),
        ),
    ]
